name: Deploy to AWS S3
description: Deploy a static website to Amazon S3 Bucket
inputs:
  bucket:
    description: AWS S3 Bucket name
    required: true
  bucket-region:
    description: AWS S3 Bucket region
    required: false
    default: eu-central-1
  dist-folder:
    description: Folder containing website files
    required: true
outputs: 
  web-site:
    description: The url of the deployed website
runs:
  using: 'node16'
  main: 'main.js'
